### Create a user
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "From Rest Client",
  "email": "from@restclient.com",
  "username": "fromrestclient",
  "password": "changeme"
}

### Login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "fromrestclient",
  "password": "changeme"
}

### Get all the users
GET http://localhost:4000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyU2lnbkluZm8iOnsibmFtZSI6IkZyb20gUmVzdCBDbGllbnQiLCJlbWFpbCI6ImZyb21AcmVzdGNsaWVudC5jb20ifSwiaWF0IjoxNzI3MTkxNzMwLCJleHAiOjE3MjcxOTUzMzB9.VyD2N7NWfSvC8hUxlZo1wVtyQfcCqbnwTseh-xogj_E

### Get a single user
GET http://localhost:4000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyU2lnbkluZm8iOnsibmFtZSI6IkZyb20gUmVzdCBDbGllbnQiLCJlbWFpbCI6ImZyb21AcmVzdGNsaWVudC5jb20ifSwiaWF0IjoxNzI3MTkxNzMwLCJleHAiOjE3MjcxOTUzMzB9.VyD2N7NWfSvC8hUxlZo1wVtyQfcCqbnwTseh-xogj_E

### Delete a user
DELETE http://localhost:4000/users/3